[package]
name = "gbhttpd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
afl = "0.15.4"
clap = { version = "4.5.4", features = ["derive"] }
fastrand = "2.0.2"
md5 = "0.7.0"
rayon = "1.10.0"
